language: python
sudo: false
deploy:
  provider: pypi
  user: arokem
  password:
    secure: AB7BnrkNOTQWXUNiaShedbIEBay+5JbulAxUHY4vEMdiI68bPLYOrIDxuT/lIfWrrgXUuicbJcWUxt6zpdUEQrEfYB6pNhrosZv4+R5HZu1FHY7EfOfsyHxb2wnezKuIEVXdevAmIg5rYNeTPcdl/CFm4xQGfdc4a3eyT5cJT58=
  on:
    tags: true
    repo: arokem/python-matlab-bridge
    # until this is fixed: https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
script:
  - true
