language: python
deploy:
  provider: pypi
  user: arokem
  password:
    secure: AB7BnrkNOTQWXUNiaShedbIEBay+5JbulAxUHY4vEMdiI68bPLYOrIDxuT/lIfWrrgXUuicbJcWUxt6zpdUEQrEfYB6pNhrosZv4+R5HZu1FHY7EfOfsyHxb2wnezKuIEVXdevAmIg5rYNeTPcdl/CFm4xQGfdc4a3eyT5cJT58=
  on:
    tags: true
    repo: arokem/python-matlab-bridge
    # until this is fixed: https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
env:
    - CONDA="python=2.7 numpy=1.7"
    - CONDA="python=3.3 numpy"
    - CONDA="python=3.4 numpy"
before_install:
  - sudo apt-add-repository -y ppa:octave/stable;
  - sudo apt-get update;
  - sudo apt-get install octave liboctave-dev default-jdk;
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - travis_retry conda create -n test $CONDA IPython pip nose pyzmq jsonschema
  - source activate test
  - if [[ $CONDA == python=3.3* ]]; then
      pip install nbformat;
    else
      travis_retry conda install nbformat;
    fi
  - travis_retry pip install coveralls

install:
  - export USE_OCTAVE=True
  - python setup.py install

script:
    # run coverage on py2.7, regular on others
  - if [[ $CONDA == python=2.7* ]]; then
      nosetests --exe -v --with-cov --cover-package pymatbridge;
    else
      nosetests --exe -v pymatbridge;
    fi

after_success:
    - coveralls
